//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObligatorioProgramacion3_Francisco_Luis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Host()
        {
            this.RadioPrograms = new HashSet<RadioProgram>();
        }
    
        public int ID { get; set; }
        public string HostName { get; set; }
        public string Bio { get; set; }
        public Nullable<int> ProgramID { get; set; }
    
        public virtual RadioProgram RadioProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadioProgram> RadioPrograms { get; set; }
    }
}
