//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObligatorioProgramacion3_Francisco_Luis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int ID { get; set; }
        public string SponsorsName { get; set; }
        public string SponsorDescription { get; set; }
        public Nullable<int> CantPlan { get; set; }
    }
}